/**
 * Business-related keywords for message classification
 * Moved to configuration for better maintainability
 */
export const BUSINESS_KEYWORDS = [
  "startup",
  "business",
  "entrepreneur",
  "company",
  "market",
  "customer",
  "revenue",
  "profit",
  "funding",
  "investment",
  "investor",
  "venture",
  "capital",
  "strategy",
  "marketing",
  "sales",
  "product",
  "service",
  "competition",
  "competitor",
  "industry",
  "growth",
  "scale",
  "team",
  "hire",
  "employee",
  "management",
  "leadership",
  "ceo",
  "cto",
  "cfo",
  "cmo",
  "finance",
  "accounting",
  "budget",
  "cost",
  "pricing",
  "valuation",
  "equity",
  "shares",
  "stock",
  "ipo",
  "acquisition",
  "merger",
  "partnership",
  "contract",
  "legal",
  "compliance",
  "regulation",
  "license",
  "patent",
  "trademark",
  "copyright",
  "intellectual property",
  "technology",
  "innovation",
  "disruption",
  "digital",
  "platform",
  "app",
  "software",
  "saas",
  "b2b",
  "b2c",
  "ecommerce",
  "marketplace",
  "analytics",
  "metrics",
  "kpi",
  "roi",
  "conversion",
  "retention",
  "acquisition",
  "monetization",
  "business model",
  "lean",
  "agile",
  "mvp",
  "prototype",
  "validation",
  "pivot",
  "iteration",
  "operations",
  "supply chain",
  "logistics",
  "procurement",
  "vendor",
  "supplier",
  "outsourcing",
  "automation",
  "efficiency",
  "productivity",
  "quality",
  "performance",
  "optimization",
  "transformation",
  "change management",
  "organizational development",
  "culture",
  "talent",
  "recruitment",
  "hiring",
  "onboarding",
  "training",
  "development",
  "succession planning",
  "performance management",
  "compensation",
  "benefits",
  "workplace",
  "remote work",
  "hybrid",
  "diversity",
  "inclusion",
  "sustainability",
  "esg",
  "corporate social responsibility",
  "brand",
  "reputation",
  "public relations",
  "crisis management",
  "stakeholder management",
  "customer experience",
  "user experience",
  "design thinking",
  "project management",
  "program management",
  "portfolio management",
  "resource allocation",
  "capacity planning",
  "risk management",
  "governance",
  "audit",
  "compliance",
  "regulatory",
  "cybersecurity",
  "data protection",
  "privacy",
  "gdpr",
  "artificial intelligence",
  "machine learning",
  "data science",
  "big data",
  "cloud computing",
  "digital transformation",
  "blockchain",
  "cryptocurrency",
  "fintech",
  "healthtech",
  "edtech",
  "proptech",
  "cleantech",
  "biotech",
  "medtech",
  "agtech",
  "foodtech",
  "retailtech",
  "insurtech",
  "regtech",
  "legaltech",
  "hrtech",
  "martech",
  "adtech",
  "salestech",
  "devops",
  "api",
  "microservices",
  "containerization",
  "kubernetes",
  "serverless",
  "edge computing",
  "iot",
  "5g",
  "ar",
  "vr",
  "metaverse",
  "nft",
  "web3",
  "defi",
  "dao",
];
